pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '74b820ea-724d-493e-8f4a-a339c5e771b5'
    definition: '435'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    artifactName: 'appVersionArtifact'
    targetPath: '$(System.DefaultWorkingDirectory)'
    
- script: |
    APP_VERSION=$(cat $(System.DefaultWorkingDirectory)/appVersion.txt)
    echo "App version: $APP_VERSION"
    
    # Clone the repository
    git clone https://bovf:$(github-Dobry-PAT)@github.com/cleverpine/homebrew-booty.git
    cd homebrew-booty/Formula
    
    # Update the booty.rb file
    sed -i "s|url \".*\"|url \"https://github.com/cleverpine/Booty/archive/refs/tags/$APP_VERSION.tar.gz\"|" booty.rb
    SHA256=$(curl -sL "https://github.com/cleverpine/Booty/archive/refs/tags/$APP_VERSION.tar.gz" | sha256sum | awk '{print $1}')
    sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|" booty.rb
    
    # Commit and push the changes
    git config --global user.email "dobry989@gmail.com"
    git config --global user.name "bovf"
    git add booty.rb
    git commit -m "Update url & sha256 for $APP_VERSION"
    git push origin main
  displayName: 'Update booty.rb File'


